name: deploy
on: [push]

jobs: 
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    permissions: 
      id-token: write 
      contents: read

    steps: 
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3

      - name: Setup Package
        run: npm install

      - name: Build docusaurus
        run: | 
          npm run build
          rm -rf node_modules

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: nhttp
          entrypoint: deploy.ts